import type { LucideIcon } from 'lucide-react';
import {
  ArrowLeftRight,
  Banknote,
  Bus,
  Briefcase,
  BookOpen,
  Cake,
  Car,
  CircleDollarSign,
  Coffee,
  CreditCard,
  Dumbbell,
  Film,
  Gamepad2,
  Gift,
  GraduationCap,
  Heart,
  Home,
  Landmark,
  MessageCircle,
  MoreHorizontal,
  Music,
  Package,
  PawPrint,
  PiggyBank,
  Pill,
  Plane,
  Receipt,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Stethoscope,
  Ticket,
  Train,
  TrendingUp,
  Utensils,
  Wallet,
  Wifi,
  Zap,
} from 'lucide-react';

/** 可供用户选择的图标集合，key 为稳定的存储标识，不要随意改名 */
export const ICONS: Record<string, LucideIcon> = {
  utensils: Utensils,
  coffee: Coffee,
  cake: Cake,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  shirt: Shirt,
  package: Package,
  receipt: Receipt,
  bus: Bus,
  car: Car,
  train: Train,
  plane: Plane,
  home: Home,
  zap: Zap,
  wifi: Wifi,
  gamepad: Gamepad2,
  film: Film,
  music: Music,
  ticket: Ticket,
  dumbbell: Dumbbell,
  plane2: Plane,
  pill: Pill,
  stethoscope: Stethoscope,
  heart: Heart,
  'book-open': BookOpen,
  'graduation-cap': GraduationCap,
  gift: Gift,
  sparkles: Sparkles,
  wallet: Wallet,
  briefcase: Briefcase,
  'trending-up': TrendingUp,
  'circle-dollar-sign': CircleDollarSign,
  banknote: Banknote,
  'credit-card': CreditCard,
  landmark: Landmark,
  'piggy-bank': PiggyBank,
  smartphone: Smartphone,
  'message-circle': MessageCircle,
  'arrow-left-right': ArrowLeftRight,
  'paw-print': PawPrint,
  'more-horizontal': MoreHorizontal,
};

export const ICON_KEYS = Object.keys(ICONS);

export function getIcon(key: string | undefined): LucideIcon {
  return (key && ICONS[key]) || MoreHorizontal;
}

/** 分类可选颜色，与全局主题变量协调 */
export const COLOR_OPTIONS = [
  '#D85A30',
  '#E24B4A',
  '#D4537E',
  '#7F77DD',
  '#534AB7',
  '#378ADD',
  '#185FA5',
  '#1D9E75',
  '#639922',
  '#BA7517',
  '#854F0B',
  '#888780',
];
